# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents-toolchain" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "fed84e1110969def3733640957f5f3c47ea02ca21bd15966d10515ad48111899"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21fe88ef2eb3226eca82eb9cb626cf133429c6cf9852577b140bd0890d05d9af"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e96e7cc5ae71c81effe870ad4d76ff4d15805ab4cd60e6f3d1728e94193f760a"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2250ca515f09b65792f6e23c6cb048fe7ace330ec606126f236702aeed778273"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agents-toolchain"
  desc "CLI for creating and running YAML-configured AI agents"
  homepage "https://github.com/Deahesi/agents-toolchain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/atc"], must_succeed: false
    end
  end

  # No zap stanza required
end
