# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents-toolchain" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "cbbe71e72ed567278c6ac1cd09e86396038381de791853a5a12be503ad0ad133"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a36211adf3b4702bd549b82d7daf312cc6f50540fb3652ad4654476905eec6b"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65df6c67f1e7c7cad2e97e925b35c668e89a19fc64ce423167b597405da283ad"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "089689038e035992aa4481ce61027edbd64b782dee0a621e0ffd89a646023fef"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agents-toolchain"
  desc "CLI for creating and running YAML-configured AI agents"
  homepage "https://github.com/Deahesi/agents-toolchain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/atc"], must_succeed: false
    end
  end

  # No zap stanza required
end
