# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents-toolchain" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "1bd32836987ebc99f46ff428351e12e7df2fb37fe594ad3ebc9692d4b99dcf9d"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "17cb3335b700387801ca5593f54103ae93c4e4c85770cd363d44120473ad9dec"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2c276b42a9c8a3fd1e23c6c3f3292d412c12436f4a62a6da00796b412371716a"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3167657a10daa221367f99feed6ae7e80f918c0fb0ef77a98ea9be3b25ce218e"
      url "https://github.com/Deahesi/agents-toolchain/releases/download/v#{version}/agents-toolchain_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agents-toolchain"
  desc "CLI for creating and running YAML-configured AI agents"
  homepage "https://github.com/Deahesi/agents-toolchain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/atc"], must_succeed: false
    end
  end

  # No zap stanza required
end
